### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-nl6i2he9#1]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by dhakb** [comment]
![Screenshot from 2022-11-24 12-31-43](https://user-images.githubusercontent.com/85057271/203787500-fcdfbe60-a4bf-4dd8-a3ca-81a91828ac82.png)
![Screenshot from 2022-11-24 12-32-10](https://user-images.githubusercontent.com/85057271/203787523-444b41bf-a852-45b6-90ae-064705caa22f.png)
